export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const SET_NEW_USER_CREATED = "SET_NEW_USER_CREATED";
export const REMOVE_NEW_USER_CREATED = "REMOVE_NEW_USER_CREATED";
